name: "build"

on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    # strategy:
    #   matrix:
    #     java: [ '14' ]
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt'
          java-version: '14' # ${{ matrix.java }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Run python
        run: |
          cd intentional/src/main/python
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run docker
        run: |
          cd intentional
          chmod +x *.sh
          chmod +x ./gradlew
          ./init.sh
          ./build.sh
          ./download.sh
          ./start.sh
          ./stop.sh
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: intentional/build/reports/jacoco/test/jacocoTestReport.csv

  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt'
          java-version: '14'
      - name: Deploy
        run: |
          cd intentional
          chmod +x ./gradlew
          ./gradlew shadowJar
          cd ..
          mkdir -p dist/
          cp intentional/build/libs/* dist/
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}